# ----
# Site

title: WKC Optical

logo: /siteicon.png
description: Your family eye care expert since 1998.
author:
  name: WKC
  email: wkcoptical1998@gmail.com
  phone: "+8559533990"
social:
  name: WKC
  links:
    - https://github.com/pr0meth4us/

timezone: Etc/UTC

collections:
  branches:
    output: false
  products:
    output: true

permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "products"
    values:
      layout: "product"
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: "index.html"
    values:
      layout: "default"

jekyll-archives:
  enabled:
    - categories

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

social_icons:
  - Instagram
  - Facebook
  - TikTok
